wk17: wk17.tex
	latexmk wk17.tex -pdf

wk17_handout: wk17_handout.tex
	latexmk wk17_handout.tex -pdf

wk18: wk18.tex
	latexmk wk18.tex -pdf

wk18_handout: wk18_handout.tex
	latexmk wk18_handout.tex -pdf

wk19: wk19.tex
	latexmk wk19.tex -pdf

wk19_handout: wk19_handout.tex
	latexmk wk19_handout.tex -pdf

wk20: wk20.tex
	latexmk wk20.tex -pdf

wk20_handout: wk20_handout.tex
	latexmk wk20_handout.tex -pdf

wk21: wk21.tex
	latexmk wk21.tex -pdf

clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	-rm -f *.bcf
	-rm -f *.fdb_latexmk
	-rm -f *.fls
	-rm -f *.run.xml
	-rm -f *.nav
	-rm -f *.snm
	-rm -f code/.Rhistory
	-rm -f .Rhistory
	-rm -f Rplots.pdf
