wk17: wk17.tex
	latexmk wk17.tex -pdf

wk18: wk18.tex
	latexmk wk18.tex -pdf

wk18_handout: wk18_handout.tex
	latexmk wk18_handout.tex -pdf

clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	-rm -f *.bcf
	-rm -f *.fdb_latexmk
	-rm -f *.fls
	-rm -f *.run.xml
	-rm -f *.nav
	-rm -f *.snm
	-rm -f code/.Rhistory
	-rm -f .Rhistory
	-rm -f Rplots.pdf
