wk17: wk17.tex
	latexmk wk17.tex -pdf

wk17_handout: wk17_handout.tex
	latexmk wk17_handout.tex -pdf

wk18: wk18.tex
	latexmk wk18.tex -pdf

wk18_handout: wk18_handout.tex
	latexmk wk18_handout.tex -pdf

wk19: wk19.tex
	latexmk wk19.tex -pdf

wk19_handout: wk19_handout.tex
	latexmk wk19_handout.tex -pdf

wk20: wk20.tex
	latexmk wk20.tex -pdf

wk20_handout: wk20_handout.tex
	latexmk wk20_handout.tex -pdf

wk21: wk21.tex
	latexmk wk21.tex -pdf

wk21_handout: wk21_handout.tex
	latexmk wk21_handout.tex -pdf

wk22: wk22.tex
	latexmk wk22.tex -pdf

wk22_handout: wk22_handout.tex
	latexmk wk22_handout.tex -pdf

wk23: wk23.tex
	latexmk wk23.tex -pdf

wk23_handout: wk23_handout.tex
	latexmk wk23_handout.tex -pdf

wk24: wk24.tex
	latexmk wk24.tex -pdf

wk24_handout: wk24_handout.tex
	latexmk wk24_handout.tex -pdf

clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	-rm -f *.bcf
	-rm -f *.fdb_latexmk
	-rm -f *.fls
	-rm -f *.run.xml
	-rm -f *.nav
	-rm -f *.snm
	-rm -f code/.Rhistory
	-rm -f .Rhistory
	-rm -f Rplots.pdf
